from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any

from .database import column_names, execute, using_postgres


def _ensure_audit_table() -> None:
    id_column = (
        "event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if using_postgres()
        else "event_id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    execute(
        f"""
        CREATE TABLE IF NOT EXISTS ai_audit_events (
            {id_column},
            event_time TEXT,
            trace_id TEXT,
            feature TEXT,
            prompt_hash TEXT,
            status TEXT,
            provider TEXT,
            model TEXT,
            reason TEXT,
            fallback_used INTEGER,
            details TEXT
        )
        """
    )
    existing = column_names("ai_audit_events")
    columns = {
        "trace_id": "TEXT",
        "provider": "TEXT",
        "model": "TEXT",
        "reason": "TEXT",
        "fallback_used": "INTEGER",
    }
    for column, column_type in columns.items():
        if column not in existing:
            execute(f'ALTER TABLE ai_audit_events ADD COLUMN "{column}" {column_type}')

def log_ai_event(
    *,
    feature: str,
    status: str,
    prompt_hash: str,
    trace_id: str = "",
    provider: str = "",
    model: str = "",
    reason: str = "",
    fallback_used: bool = False,
    metadata: dict[str, Any] | None = None,
) -> None:
    _ensure_audit_table()
    timestamp = datetime.now(UTC).isoformat()
    event = {
        "timestamp": timestamp,
        "trace_id": trace_id,
        "feature": feature,
        "status": status,
        "reason": reason,
        "prompt_hash": prompt_hash,
        "provider": provider,
        "model": model,
        "fallback_used": fallback_used,
        "metadata": metadata or {},
    }
    placeholder = "%s" if using_postgres() else "?"
    execute(
        f"""
        INSERT INTO ai_audit_events (
            event_time, trace_id, feature, prompt_hash, status, provider,
            model, reason, fallback_used, details
        )
        VALUES ({", ".join([placeholder] * 10)})
        """,
        (
            timestamp,
            trace_id,
            feature,
            prompt_hash,
            status,
            provider,
            model,
            reason,
            1 if fallback_used else 0,
            json.dumps(event, default=str),
        ),
    )
