export type AiProvenance = {
  source?: string | null;
  provider?: string | null;
  model?: string | null;
  traceId?: string | null;
  trace_id?: string | null;
};

interface AiProvenanceBadgeProps {
  provenance?: AiProvenance | null;
  compact?: boolean;
}

export function AiProvenanceBadge({ provenance, compact = false }: AiProvenanceBadgeProps) {
  const source = provenance?.source || "deterministic_fallback";
  const isLlm = source === "llm";
  const isValidationFallback = source === "llm_validation_fallback";
  const provider = provenance?.provider || null;
  const model = provenance?.model || null;
  const traceId = provenance?.traceId || provenance?.trace_id || null;
  const label = isLlm
    ? `LLM${provider ? `: ${provider}` : ""}`
    : isValidationFallback
      ? `Validated fallback${provider ? `: ${provider}` : ""}`
      : "Rule-based fallback";
  const detail = [
    isLlm
      ? "Generated by LLM"
      : isValidationFallback
        ? "LLM responded, but output validation kept the deterministic summary"
        : "Generated by deterministic rules",
    model ? `Model: ${model}` : null,
    traceId ? `Trace: ${traceId}` : null,
  ]
    .filter(Boolean)
    .join(" | ");

  return (
    <span
      title={detail}
      className={`inline-flex w-fit items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold ${
        isLlm
          ? "border-blue-200 bg-blue-50 text-blue-700"
          : isValidationFallback
            ? "border-purple-200 bg-purple-50 text-purple-700"
          : "border-amber-200 bg-amber-50 text-amber-800"
      } ${compact ? "px-2 py-0.5 text-[10px]" : ""}`}
    >
      {label}
    </span>
  );
}
