from __future__ import annotations

import sys
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.app.services.database import column_names, execute, using_postgres


def _add_missing_columns(table_name: str, columns: dict[str, str]) -> None:
    existing = column_names(table_name)
    for column, column_type in columns.items():
        if column not in existing:
            execute(f'ALTER TABLE "{table_name}" ADD COLUMN "{column}" {column_type}')
            print(f"Added {table_name}.{column}")


def migrate_guardrails_schema() -> None:
    if not using_postgres():
        raise RuntimeError("Guardrails schema migration is intended for PostgreSQL.")

    execute(
        """
        CREATE TABLE IF NOT EXISTS ai_audit_events (
            event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_time TEXT,
            trace_id TEXT,
            feature TEXT,
            prompt_hash TEXT,
            status TEXT,
            provider TEXT,
            model TEXT,
            reason TEXT,
            fallback_used INTEGER,
            details TEXT
        )
        """
    )
    _add_missing_columns(
        "ai_audit_events",
        {
            "trace_id": "TEXT",
            "provider": "TEXT",
            "model": "TEXT",
            "reason": "TEXT",
            "fallback_used": "INTEGER",
            "details": "TEXT",
        },
    )

    execute(
        """
        CREATE TABLE IF NOT EXISTS ai_review_queue (
            item_id TEXT PRIMARY KEY,
            trace_id TEXT,
            feature TEXT,
            reason TEXT,
            prompt_hash TEXT,
            status TEXT,
            created_at TEXT,
            reviewed_at TEXT,
            reviewer TEXT,
            payload TEXT,
            decision TEXT
        )
        """
    )
    _add_missing_columns(
        "ai_review_queue",
        {
            "trace_id": "TEXT",
            "reason": "TEXT",
            "prompt_hash": "TEXT",
            "feature": "TEXT",
            "status": "TEXT",
            "created_at": "TEXT",
            "reviewed_at": "TEXT",
            "reviewer": "TEXT",
            "payload": "TEXT",
            "decision": "TEXT",
        },
    )

    execute(
        'CREATE INDEX IF NOT EXISTS "idx_ai_audit_events_trace_id" ON "ai_audit_events" ("trace_id")'
    )
    execute(
        'CREATE INDEX IF NOT EXISTS "idx_ai_audit_events_feature_status" ON "ai_audit_events" ("feature", "status")'
    )
    execute(
        'CREATE INDEX IF NOT EXISTS "idx_ai_review_queue_status" ON "ai_review_queue" ("status")'
    )
    execute(
        'CREATE INDEX IF NOT EXISTS "idx_ai_review_queue_trace_id" ON "ai_review_queue" ("trace_id")'
    )

    execute(
        """
        CREATE TABLE IF NOT EXISTS knowledge_chunks (
            chunk_id TEXT PRIMARY KEY,
            source_type TEXT,
            source_id TEXT,
            title TEXT,
            chunk_text TEXT,
            metadata TEXT,
            embedding_provider TEXT,
            embedding_model TEXT,
            embedding_json TEXT,
            content_hash TEXT,
            is_sanitized INTEGER,
            safety_notes TEXT,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    _add_missing_columns(
        "knowledge_chunks",
        {
            "source_type": "TEXT",
            "source_id": "TEXT",
            "title": "TEXT",
            "chunk_text": "TEXT",
            "metadata": "TEXT",
            "embedding_provider": "TEXT",
            "embedding_model": "TEXT",
            "embedding_json": "TEXT",
            "content_hash": "TEXT",
            "is_sanitized": "INTEGER",
            "safety_notes": "TEXT",
            "updated_at": "TEXT",
        },
    )
    execute(
        'CREATE INDEX IF NOT EXISTS "idx_knowledge_chunks_source_type" ON "knowledge_chunks" ("source_type")'
    )
    execute(
        'CREATE INDEX IF NOT EXISTS "idx_knowledge_chunks_source_id" ON "knowledge_chunks" ("source_id")'
    )
    execute(
        'CREATE INDEX IF NOT EXISTS "idx_knowledge_chunks_content_hash" ON "knowledge_chunks" ("content_hash")'
    )

    print("Guardrails schema migration complete.")


if __name__ == "__main__":
    load_dotenv(PROJECT_ROOT / ".env")
    migrate_guardrails_schema()
