from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from pathlib import Path
from typing import Any

import pandas as pd
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.app.services.database import FUTURE_ESG_TABLES_POSTGRES  # noqa: E402


def _psycopg():
    try:
        import psycopg
    except ImportError as exc:
        raise RuntimeError(
            "PostgreSQL support requires psycopg. Run `pip install -r requirements.txt`."
        ) from exc
    return psycopg


def quote_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def postgres_type(sqlite_type: str, values: pd.Series) -> str:
    normalized = (sqlite_type or "").upper()
    if "INT" in normalized:
        return "BIGINT"
    if "REAL" in normalized or "FLOA" in normalized or "DOUB" in normalized:
        return "DOUBLE PRECISION"
    if "BLOB" in normalized:
        return "BYTEA"
    if pd.api.types.is_integer_dtype(values):
        return "BIGINT"
    if pd.api.types.is_float_dtype(values):
        return "DOUBLE PRECISION"
    if pd.api.types.is_bool_dtype(values):
        return "BOOLEAN"
    return "TEXT"


def sqlite_tables(connection: sqlite3.Connection) -> list[str]:
    rows = connection.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table' AND name != 'sqlite_sequence'
        ORDER BY name
        """
    ).fetchall()
    return [row[0] for row in rows]


def sqlite_columns(connection: sqlite3.Connection, table_name: str) -> list[dict[str, Any]]:
    rows = connection.execute(f"PRAGMA table_info({quote_identifier(table_name)})").fetchall()
    return [
        {
            "name": row[1],
            "type": row[2],
            "notnull": bool(row[3]),
            "default": row[4],
            "pk": bool(row[5]),
        }
        for row in rows
    ]


def create_table(
    postgres_connection: Any,
    sqlite_connection: sqlite3.Connection,
    table_name: str,
    data_frame: pd.DataFrame,
) -> None:
    columns = sqlite_columns(sqlite_connection, table_name)
    column_defs = []
    primary_keys = []

    for column in columns:
        column_name = column["name"]
        column_type = postgres_type(column["type"], data_frame[column_name])
        if table_name == "ai_audit_events" and column_name == "event_id":
            column_type = "BIGINT GENERATED BY DEFAULT AS IDENTITY"
        if column["pk"]:
            primary_keys.append(column_name)
        column_defs.append(f"{quote_identifier(column_name)} {column_type}")

    if primary_keys:
        quoted_keys = ", ".join(quote_identifier(key) for key in primary_keys)
        column_defs.append(f"PRIMARY KEY ({quoted_keys})")

    quoted_table = quote_identifier(table_name)
    postgres_connection.execute(f"DROP TABLE IF EXISTS {quoted_table} CASCADE")
    postgres_connection.execute(f"CREATE TABLE {quoted_table} ({', '.join(column_defs)})")


def copy_table(postgres_connection: Any, table_name: str, data_frame: pd.DataFrame) -> None:
    if data_frame.empty:
        return

    clean_frame = data_frame.where(pd.notna(data_frame), None)
    quoted_table = quote_identifier(table_name)
    quoted_columns = [quote_identifier(column) for column in clean_frame.columns]
    placeholders = ", ".join(["%s"] * len(quoted_columns))
    rows = list(clean_frame.itertuples(index=False, name=None))

    with postgres_connection.cursor() as cursor:
        cursor.executemany(
            f"""
            INSERT INTO {quoted_table} ({", ".join(quoted_columns)})
            VALUES ({placeholders})
            """,
            rows,
        )


def ensure_future_tables(postgres_connection: Any) -> None:
    for statement in FUTURE_ESG_TABLES_POSTGRES.values():
        postgres_connection.execute(statement)


def migrate(sqlite_path: Path, database_url: str, replace: bool) -> list[tuple[str, int, int]]:
    if not sqlite_path.exists():
        raise FileNotFoundError(f"SQLite database not found at {sqlite_path}")

    psycopg = _psycopg()
    results: list[tuple[str, int, int]] = []
    with sqlite3.connect(sqlite_path) as sqlite_connection:
        tables = sqlite_tables(sqlite_connection)
        with psycopg.connect(database_url) as postgres_connection:
            for table_name in tables:
                quoted_table = quote_identifier(table_name)
                data_frame = pd.read_sql_query(f"SELECT * FROM {quoted_table}", sqlite_connection)
                if replace:
                    create_table(postgres_connection, sqlite_connection, table_name, data_frame)
                elif not _postgres_table_exists(postgres_connection, table_name):
                    create_table(postgres_connection, sqlite_connection, table_name, data_frame)

                copy_table(postgres_connection, table_name, data_frame)
                source_count = len(data_frame)
                target_count = postgres_connection.execute(
                    f"SELECT COUNT(*) FROM {quoted_table}"
                ).fetchone()[0]
                results.append((table_name, source_count, target_count))
                print(f"MIGRATED {table_name}: sqlite={source_count}, postgres={target_count}")

            ensure_future_tables(postgres_connection)
            postgres_connection.commit()

    return results


def _postgres_table_exists(connection: Any, table_name: str) -> bool:
    row = connection.execute(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = %s
        """,
        (table_name,),
    ).fetchone()
    return row is not None


def main() -> None:
    load_dotenv(PROJECT_ROOT / ".env")
    parser = argparse.ArgumentParser(description="Migrate Ozone AI SQLite data into PostgreSQL.")
    parser.add_argument(
        "--sqlite-db",
        type=Path,
        default=PROJECT_ROOT / "data" / "ozone_ai.sqlite3",
        help="Source SQLite database path.",
    )
    parser.add_argument(
        "--database-url",
        default=os.getenv("DATABASE_URL"),
        help="Target PostgreSQL URL. Defaults to DATABASE_URL from .env.",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="Drop and recreate migrated tables before copying data.",
    )
    args = parser.parse_args()

    if not args.database_url:
        raise SystemExit("DATABASE_URL is required. Set it in .env or pass --database-url.")

    results = migrate(args.sqlite_db, args.database_url, args.replace)
    mismatches = [
        (table_name, source_count, target_count)
        for table_name, source_count, target_count in results
        if source_count != target_count
    ]
    if mismatches:
        print("\nRow-count mismatches:")
        for table_name, source_count, target_count in mismatches:
            print(f"- {table_name}: sqlite={source_count}, postgres={target_count}")
        raise SystemExit(1)

    print(f"\nDone. Migrated {len(results)} SQLite tables into PostgreSQL.")


if __name__ == "__main__":
    main()
