-- PostgreSQL schema for Supplier Risk Intelligence
-- Run this in pgAdmin Query Tool against your target database.
-- Inserts/data load are managed by the live PostgreSQL application.

BEGIN;

DROP TABLE IF EXISTS "ai_audit_events" CASCADE;
CREATE TABLE "ai_audit_events" (
    "event_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "event_time" TEXT,
    "feature" TEXT,
    "prompt_hash" TEXT,
    "status" TEXT,
    "details" TEXT,
    "trace_id" TEXT,
    "provider" TEXT,
    "model" TEXT,
    "reason" TEXT,
    "fallback_used" BIGINT,
    PRIMARY KEY ("event_id")
);

DROP TABLE IF EXISTS "ai_review_queue" CASCADE;
CREATE TABLE "ai_review_queue" (
    "item_id" TEXT,
    "trace_id" TEXT,
    "feature" TEXT,
    "reason" TEXT,
    "prompt_hash" TEXT,
    "status" TEXT,
    "created_at" TEXT,
    "reviewed_at" TEXT,
    "reviewer" TEXT,
    "payload" TEXT,
    "decision" TEXT,
    PRIMARY KEY ("item_id")
);

CREATE INDEX IF NOT EXISTS "idx_ai_audit_events_trace_id" ON "ai_audit_events" ("trace_id");
CREATE INDEX IF NOT EXISTS "idx_ai_audit_events_feature_status" ON "ai_audit_events" ("feature", "status");
CREATE INDEX IF NOT EXISTS "idx_ai_review_queue_status" ON "ai_review_queue" ("status");
CREATE INDEX IF NOT EXISTS "idx_ai_review_queue_trace_id" ON "ai_review_queue" ("trace_id");

DROP TABLE IF EXISTS "alerts" CASCADE;
CREATE TABLE "alerts" (
    "alert_id" BIGINT,
    "supplier_id" BIGINT,
    "type" TEXT,
    "severity" TEXT,
    "description" TEXT,
    "status" TEXT
);

DROP TABLE IF EXISTS "audit_capa" CASCADE;
CREATE TABLE "audit_capa" (
    "capa_id" BIGINT,
    "audit_id" BIGINT,
    "supplier_id" BIGINT,
    "issue" TEXT,
    "severity" TEXT,
    "owner" TEXT,
    "description" TEXT,
    "due_date" TEXT,
    "status" TEXT,
    "evidence_required" TEXT,
    "supplier_response" DOUBLE PRECISION,
    "evidence_notes" DOUBLE PRECISION,
    "created_date" TEXT,
    "closed_date" TEXT
);

DROP TABLE IF EXISTS "audit_evidence" CASCADE;
CREATE TABLE "audit_evidence" (
    "audit_evidence_id" BIGINT,
    "audit_id" BIGINT,
    "supplier_id" BIGINT,
    "linked_capa_id" DOUBLE PRECISION,
    "evidence_type" TEXT,
    "file_name" TEXT,
    "local_path" TEXT,
    "blob_name" TEXT,
    "blob_url" TEXT,
    "storage_provider" TEXT,
    "upload_date" TEXT,
    "document_status" TEXT,
    "validation_status" TEXT,
    "validation_notes" TEXT,
    "extracted_text_preview" TEXT
);

DROP TABLE IF EXISTS "audits" CASCADE;
CREATE TABLE "audits" (
    "audit_id" BIGINT,
    "supplier_id" BIGINT,
    "audit_date" TEXT,
    "type" TEXT,
    "score" DOUBLE PRECISION,
    "non_compliance" BIGINT,
    "audit_priority" TEXT,
    "audit_status" TEXT,
    "audit_decision" TEXT,
    "decision_notes" TEXT,
    "decision_date" TEXT,
    "capa_required" TEXT,
    "capa_due_date" DOUBLE PRECISION,
    "capa_status" TEXT
);

DROP TABLE IF EXISTS "certifications" CASCADE;
CREATE TABLE "certifications" (
    "cert_id" BIGINT,
    "cert_name" TEXT
);

DROP TABLE IF EXISTS "commodities" CASCADE;
CREATE TABLE "commodities" (
    "commodity_id" BIGINT,
    "commodity_name" TEXT,
    "risk_level" TEXT,
    "deforestation_risk_score" DOUBLE PRECISION
);

DROP TABLE IF EXISTS "document_uploads" CASCADE;
CREATE TABLE "document_uploads" (
    "upload_id" TEXT,
    "supplier_id" BIGINT,
    "module" TEXT,
    "file_name" TEXT,
    "file_path" TEXT,
    "uploaded_at" TEXT,
    "uploaded_by" TEXT,
    "extracted_text_available" BIGINT,
    "notes" TEXT,
    PRIMARY KEY ("upload_id")
);

DROP TABLE IF EXISTS "due_diligence_case_notes" CASCADE;
CREATE TABLE "due_diligence_case_notes" (
    "note_id" TEXT,
    "case_id" TEXT,
    "supplier_id" TEXT,
    "note_date" TEXT,
    "note_type" TEXT,
    "note" TEXT
);

DROP TABLE IF EXISTS "due_diligence_cases" CASCADE;
CREATE TABLE "due_diligence_cases" (
    "case_id" TEXT,
    "supplier_id" TEXT,
    "supplier_name" TEXT,
    "case_date" TEXT,
    "overall_risk_score" TEXT,
    "decision" TEXT,
    "status" TEXT,
    "summary" TEXT
);

DROP TABLE IF EXISTS "due_diligence_decisions" CASCADE;
CREATE TABLE "due_diligence_decisions" (
    "decision_id" TEXT,
    "case_id" TEXT,
    "supplier_id" TEXT,
    "decision_date" TEXT,
    "decision" TEXT,
    "rationale" TEXT,
    "recommended_actions" TEXT
);

DROP TABLE IF EXISTS "esg_action_comments" CASCADE;
CREATE TABLE "esg_action_comments" (
    "comment_id" TEXT,
    "action_id" TEXT,
    "supplier_id" BIGINT,
    "comment_text" TEXT,
    "created_by" TEXT,
    "created_at" TEXT,
    PRIMARY KEY ("comment_id")
);

DROP TABLE IF EXISTS "esg_alert_history" CASCADE;
CREATE TABLE "esg_alert_history" (
    "history_id" TEXT,
    "alert_id" TEXT,
    "supplier_id" BIGINT,
    "previous_status" TEXT,
    "new_status" TEXT,
    "changed_by" TEXT,
    "changed_at" TEXT,
    "notes" TEXT,
    PRIMARY KEY ("history_id")
);

DROP TABLE IF EXISTS "esg_environmental" CASCADE;
CREATE TABLE "esg_environmental" (
    "supplier_id" BIGINT,
    "carbon" DOUBLE PRECISION,
    "energy" DOUBLE PRECISION,
    "renewable" DOUBLE PRECISION,
    "water" DOUBLE PRECISION,
    "waste" DOUBLE PRECISION,
    "recycle" DOUBLE PRECISION,
    "pollution" DOUBLE PRECISION,
    "land" DOUBLE PRECISION,
    "deforestation" DOUBLE PRECISION,
    "fines" DOUBLE PRECISION
);

DROP TABLE IF EXISTS "esg_governance" CASCADE;
CREATE TABLE "esg_governance" (
    "supplier_id" BIGINT,
    "corruption" DOUBLE PRECISION,
    "compliance" DOUBLE PRECISION,
    "board" DOUBLE PRECISION,
    "transparency" DOUBLE PRECISION,
    "legal" DOUBLE PRECISION,
    "tax" DOUBLE PRECISION,
    "disclosure" DOUBLE PRECISION,
    "data" DOUBLE PRECISION,
    "policy" DOUBLE PRECISION,
    "reporting" DOUBLE PRECISION
);

DROP TABLE IF EXISTS "esg_monitoring_feature_scores" CASCADE;
CREATE TABLE "esg_monitoring_feature_scores" (
    "score_id" TEXT,
    "supplier_id" BIGINT,
    "feature_name" TEXT,
    "feature_value" DOUBLE PRECISION,
    "feature_weight" DOUBLE PRECISION,
    "contribution_score" DOUBLE PRECISION,
    "calculated_at" TEXT,
    PRIMARY KEY ("score_id")
);

DROP TABLE IF EXISTS "esg_monitoring_model_runs" CASCADE;
CREATE TABLE "esg_monitoring_model_runs" (
    "model_run_id" TEXT,
    "model_name" TEXT,
    "model_version" TEXT,
    "run_started_at" TEXT,
    "run_completed_at" TEXT,
    "status" TEXT,
    "input_snapshot_month" TEXT,
    "notes" TEXT,
    PRIMARY KEY ("model_run_id")
);

DROP TABLE IF EXISTS "esg_monitoring_predictions" CASCADE;
CREATE TABLE "esg_monitoring_predictions" (
    "prediction_id" TEXT,
    "model_run_id" TEXT,
    "supplier_id" BIGINT,
    "prediction_date" TEXT,
    "anomaly_score" DOUBLE PRECISION,
    "risk_probability" DOUBLE PRECISION,
    "signal_label" TEXT,
    "top_drivers" TEXT,
    "explanation" TEXT,
    PRIMARY KEY ("prediction_id")
);

DROP TABLE IF EXISTS "esg_monitoring_snapshots" CASCADE;
CREATE TABLE "esg_monitoring_snapshots" (
    "snapshot_id" TEXT,
    "supplier_id" BIGINT,
    "snapshot_month" TEXT,
    "environmental_risk" DOUBLE PRECISION,
    "social_risk" DOUBLE PRECISION,
    "governance_risk" DOUBLE PRECISION,
    "esg_health_score" DOUBLE PRECISION,
    "anomaly_score" DOUBLE PRECISION,
    "open_alert_count" BIGINT,
    "stale_evidence_count" BIGINT,
    "certification_gap_count" BIGINT,
    "trend_label" TEXT,
    "created_at" TEXT,
    PRIMARY KEY ("snapshot_id")
);

DROP TABLE IF EXISTS "esg_social" CASCADE;
CREATE TABLE "esg_social" (
    "supplier_id" BIGINT,
    "labor" DOUBLE PRECISION,
    "injury" DOUBLE PRECISION,
    "turnover" DOUBLE PRECISION,
    "diversity" DOUBLE PRECISION,
    "child" DOUBLE PRECISION,
    "hours" DOUBLE PRECISION,
    "audit" DOUBLE PRECISION,
    "complaints" DOUBLE PRECISION,
    "wage" DOUBLE PRECISION,
    "satisfaction" DOUBLE PRECISION
);

DROP TABLE IF EXISTS "external_esg_signals" CASCADE;
CREATE TABLE "external_esg_signals" (
    "signal_id" TEXT,
    "supplier_id" BIGINT,
    "signal_date" TEXT,
    "source_type" TEXT,
    "source_name" TEXT,
    "pillar" TEXT,
    "signal_title" TEXT,
    "signal_summary" TEXT,
    "severity" TEXT,
    "confidence" DOUBLE PRECISION
);

DROP TABLE IF EXISTS "external_signal_ingestion_log" CASCADE;
CREATE TABLE "external_signal_ingestion_log" (
    "ingestion_id" TEXT,
    "source_name" TEXT,
    "source_type" TEXT,
    "ingested_at" TEXT,
    "records_received" BIGINT,
    "records_accepted" BIGINT,
    "records_rejected" BIGINT,
    "status" TEXT,
    "notes" TEXT,
    PRIMARY KEY ("ingestion_id")
);

DROP TABLE IF EXISTS "monitoring_actions" CASCADE;
CREATE TABLE "monitoring_actions" (
    "action_id" TEXT,
    "alert_id" TEXT,
    "supplier_id" BIGINT,
    "action_type" TEXT,
    "owner" TEXT,
    "due_date" TEXT,
    "status" TEXT,
    "notes" TEXT,
    "linked_module" TEXT,
    "linked_record_id" TEXT
);

DROP TABLE IF EXISTS "monitoring_alerts" CASCADE;
CREATE TABLE "monitoring_alerts" (
    "alert_id" TEXT,
    "supplier_id" BIGINT,
    "rule_id" TEXT,
    "alert_date" TEXT,
    "pillar" TEXT,
    "indicator" TEXT,
    "severity" TEXT,
    "status" TEXT,
    "previous_value" BIGINT,
    "current_value" BIGINT,
    "change_value" BIGINT,
    "trigger_reason" TEXT,
    "recommended_route" TEXT,
    "linked_action_id" TEXT
);

DROP TABLE IF EXISTS "monitoring_observations" CASCADE;
CREATE TABLE "monitoring_observations" (
    "observation_id" TEXT,
    "supplier_id" BIGINT,
    "observation_date" TEXT,
    "pillar" TEXT,
    "indicator" TEXT,
    "previous_value" BIGINT,
    "current_value" BIGINT,
    "unit" TEXT,
    "source" TEXT,
    "source_detail" TEXT,
    "confidence" DOUBLE PRECISION
);

DROP TABLE IF EXISTS "monitoring_rules" CASCADE;
CREATE TABLE "monitoring_rules" (
    "rule_id" TEXT,
    "rule_name" TEXT,
    "pillar" TEXT,
    "indicator" TEXT,
    "condition_type" TEXT,
    "threshold_value" BIGINT,
    "severity" TEXT,
    "recommended_route" TEXT,
    "enabled" TEXT
);

DROP TABLE IF EXISTS "supplier_certifications" CASCADE;
CREATE TABLE "supplier_certifications" (
    "id" BIGINT,
    "supplier_id" BIGINT,
    "cert_id" BIGINT,
    "issue_date" TEXT,
    "expiry_date" TEXT,
    "status" TEXT,
    "certificate_number" TEXT,
    "issuing_body" TEXT,
    "scope" TEXT,
    "evidence_id" DOUBLE PRECISION,
    "validation_status" TEXT
);

DROP TABLE IF EXISTS "supplier_commodity_map" CASCADE;
CREATE TABLE "supplier_commodity_map" (
    "supplier_id" BIGINT,
    "commodity_id" BIGINT,
    "volume" DOUBLE PRECISION
);

DROP TABLE IF EXISTS "supplier_evidence" CASCADE;
CREATE TABLE "supplier_evidence" (
    "evidence_id" BIGINT,
    "supplier_id" DOUBLE PRECISION,
    "temporary_supplier_key" TEXT,
    "evidence_type" TEXT,
    "linked_entity_type" TEXT,
    "linked_entity_name" TEXT,
    "file_name" TEXT,
    "local_path" TEXT,
    "blob_name" TEXT,
    "blob_url" TEXT,
    "storage_provider" TEXT,
    "upload_date" TEXT,
    "document_status" TEXT,
    "extracted_text_preview" TEXT,
    "extracted_certificate_name" TEXT,
    "extracted_certificate_number" TEXT,
    "extracted_issuer" TEXT,
    "extracted_issue_date" TEXT,
    "extracted_expiry_date" TEXT,
    "extracted_scope_site" TEXT,
    "validation_status" TEXT,
    "validation_notes" TEXT,
    "review_status" TEXT
);

DROP TABLE IF EXISTS "supplier_evidence_refresh" CASCADE;
CREATE TABLE "supplier_evidence_refresh" (
    "refresh_id" TEXT,
    "supplier_id" BIGINT,
    "evidence_type" TEXT,
    "last_received_date" TEXT,
    "refresh_due_date" TEXT,
    "freshness_status" TEXT,
    "linked_evidence_id" DOUBLE PRECISION,
    "recommended_action" TEXT
);

DROP TABLE IF EXISTS "supplier_features" CASCADE;
CREATE TABLE "supplier_features" (
    "supplier_id" BIGINT,
    "avg_delay" DOUBLE PRECISION,
    "avg_defect" DOUBLE PRECISION,
    "esg_score" DOUBLE PRECISION,
    "risk_score" DOUBLE PRECISION,
    "risk_category" TEXT
);

DROP TABLE IF EXISTS "supplier_sites" CASCADE;
CREATE TABLE "supplier_sites" (
    "site_id" TEXT,
    "supplier_id" BIGINT,
    "site_name" TEXT,
    "site_type" TEXT,
    "country" TEXT,
    "region" TEXT,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "geo_evidence_status" TEXT,
    "polygon_evidence_status" TEXT,
    "deforestation_risk_status" TEXT,
    "last_verified_date" TEXT
);

DROP TABLE IF EXISTS "suppliers" CASCADE;
CREATE TABLE "suppliers" (
    "supplier_id" BIGINT,
    "supplier_name" TEXT,
    "country" TEXT,
    "parent_supplier_id" DOUBLE PRECISION,
    "tier" TEXT,
    "size" TEXT,
    "annual_revenue" DOUBLE PRECISION,
    "dependency_score" DOUBLE PRECISION,
    "criticality_score" DOUBLE PRECISION,
    "onboarding_date" TEXT,
    "status" TEXT,
    "esg_baseline_date" TEXT,
    "evidence_status" TEXT,
    "eudr_relevant" TEXT,
    "traceability_required" TEXT,
    "site_region" TEXT,
    "supplier_role" TEXT,
    "plot_traceability_available" TEXT,
    "geolocation_evidence_available" TEXT,
    "chain_of_custody_available" TEXT,
    "deforestation_declaration_available" TEXT,
    "labor_questionnaire_status" TEXT,
    "traceability_notes" DOUBLE PRECISION,
    "onboarding_requirements_json" DOUBLE PRECISION,
    "approval_status" TEXT,
    "reviewer_name" DOUBLE PRECISION,
    "approval_decision" TEXT,
    "approval_decision_date" DOUBLE PRECISION,
    "approval_conditions" DOUBLE PRECISION,
    "approval_blockers" DOUBLE PRECISION
);

DROP TABLE IF EXISTS "traceability_decisions" CASCADE;
CREATE TABLE "traceability_decisions" (
    "decision_id" BIGINT,
    "supplier_id" BIGINT,
    "decision_date" TEXT,
    "decision" TEXT,
    "confidence" TEXT,
    "rationale_json" TEXT,
    "blockers_json" TEXT,
    "missing_evidence_json" TEXT,
    "next_actions_json" TEXT,
    "source" TEXT,
    "provider" TEXT,
    "model" TEXT
);

DROP TABLE IF EXISTS "traceability_events" CASCADE;
CREATE TABLE "traceability_events" (
    "event_id" TEXT,
    "lot_id" TEXT,
    "supplier_id" BIGINT,
    "event_type" TEXT,
    "event_date" TEXT,
    "from_site_id" TEXT,
    "to_site_id" TEXT,
    "country" TEXT,
    "evidence_type" TEXT,
    "evidence_status" TEXT,
    "notes" TEXT
);

DROP TABLE IF EXISTS "traceability_gap_action_history" CASCADE;
CREATE TABLE "traceability_gap_action_history" (
    "history_id" TEXT,
    "gap_id" TEXT,
    "supplier_id" TEXT,
    "action" TEXT,
    "previous_status" TEXT,
    "new_status" TEXT,
    "notes" TEXT,
    "action_date" TEXT
);

DROP TABLE IF EXISTS "traceability_gap_actions" CASCADE;
CREATE TABLE "traceability_gap_actions" (
    "gap_id" TEXT,
    "supplier_id" BIGINT,
    "lot_id" TEXT,
    "site_id" TEXT,
    "gap_type" TEXT,
    "severity" TEXT,
    "status" TEXT,
    "owner" TEXT,
    "due_date" TEXT,
    "description" TEXT,
    "recommended_action" TEXT
);

DROP TABLE IF EXISTS "traceability_lots" CASCADE;
CREATE TABLE "traceability_lots" (
    "lot_id" TEXT,
    "supplier_id" BIGINT,
    "commodity_id" BIGINT,
    "site_id" TEXT,
    "lot_code" TEXT,
    "quantity" DOUBLE PRECISION,
    "unit" TEXT,
    "production_date" TEXT,
    "shipment_reference" TEXT,
    "current_status" TEXT,
    "evidence_status" TEXT
);

DROP TABLE IF EXISTS "traceability_score_history" CASCADE;
CREATE TABLE "traceability_score_history" (
    "snapshot_id" TEXT,
    "supplier_id" TEXT,
    "snapshot_date" TEXT,
    "traceability_score" TEXT,
    "score_level" TEXT,
    "eudr_status" TEXT,
    "open_gap_count" TEXT,
    "coverage_percent" TEXT,
    "trigger" TEXT
);

DROP TABLE IF EXISTS "transactions" CASCADE;
CREATE TABLE "transactions" (
    "transaction_id" BIGINT,
    "supplier_id" BIGINT,
    "date" TEXT,
    "order_value" DOUBLE PRECISION,
    "delay_days" BIGINT,
    "defect_rate" DOUBLE PRECISION,
    "cost_variance" DOUBLE PRECISION
);

DROP TABLE IF EXISTS "user_activity_log" CASCADE;
CREATE TABLE "user_activity_log" (
    "activity_id" TEXT,
    "user_name" TEXT,
    "module" TEXT,
    "action" TEXT,
    "entity_type" TEXT,
    "entity_id" TEXT,
    "created_at" TEXT,
    "details" TEXT,
    PRIMARY KEY ("activity_id")
);

COMMIT;
